example_files = \
 EXAMPLES/3.gz \
 EXAMPLES/1.gz \
 EXAMPLES/trendlist_tfa_fits \
 EXAMPLES/1.add \
 EXAMPLES/7.gz \
 EXAMPLES/8.gz \
 EXAMPLES/2.twoharmsignal \
 EXAMPLES/2.fftfilter \
 EXAMPLES/6.fits \
 EXAMPLES/lc_list_tfa_fits \
 EXAMPLES/2 \
 EXAMPLES/1.png \
 EXAMPLES/5.fits \
 EXAMPLES/OUTDIR1/3.arimaresiduals.png \
 EXAMPLES/OUTDIR1/6.autocorr \
 EXAMPLES/OUTDIR1/8.wwz.fits \
 EXAMPLES/OUTDIR1/InjectRRLyrae.9.txt \
 EXAMPLES/OUTDIR1/3.ls \
 EXAMPLES/OUTDIR1/2.wwz \
 EXAMPLES/OUTDIR1/7.bls \
 EXAMPLES/OUTDIR1/7.arimaresiduals.png \
 EXAMPLES/OUTDIR1/7.cleanharm \
 EXAMPLES/OUTDIR1/stdin.mcmc \
 EXAMPLES/OUTDIR1/4.dftclean.cbeam \
 EXAMPLES/OUTDIR1/8.arimamodel \
 EXAMPLES/OUTDIR1/1.bjdtdb \
 EXAMPLES/OUTDIR1/9.arimamodel \
 EXAMPLES/OUTDIR1/6.phase.txt \
 EXAMPLES/OUTDIR1/3.starspot.tfa.model \
 EXAMPLES/OUTDIR1/8.wwz.pm3d \
 EXAMPLES/OUTDIR1/6.sysrem.model \
 EXAMPLES/OUTDIR1/3.mandelagoltransit.model \
 EXAMPLES/OUTDIR1/5.bls.model \
 EXAMPLES/OUTDIR1/4.arimaresiduals.png \
 EXAMPLES/OUTDIR1/6.arimamodel \
 EXAMPLES/OUTDIR1/4.microlensinject.microlens \
 EXAMPLES/OUTDIR1/9.bls.phcurve \
 EXAMPLES/OUTDIR1/10.cleanharm \
 EXAMPLES/OUTDIR1/3.bls.phcurve \
 EXAMPLES/OUTDIR1/8.arimaforecast.png \
 EXAMPLES/OUTDIR1/4.arimamodel \
 EXAMPLES/OUTDIR1/5.clip.txt \
 EXAMPLES/OUTDIR1/3.starspot.tfa.coeff \
 EXAMPLES/OUTDIR1/1.png \
 EXAMPLES/OUTDIR1/6.arimaforecast.png \
 EXAMPLES/OUTDIR1/1.bls \
 EXAMPLES/OUTDIR1/10.bls \
 EXAMPLES/OUTDIR1/9.phase.txt \
 EXAMPLES/OUTDIR1/file_3_00003_simout.txt \
 EXAMPLES/OUTDIR1/7.arimaforecast.png \
 EXAMPLES/OUTDIR1/9.bls.model \
 EXAMPLES/OUTDIR1/2.arimaforecast.png \
 EXAMPLES/OUTDIR1/2.ls \
 EXAMPLES/OUTDIR1/5.bls \
 EXAMPLES/OUTDIR1/3.arimaforecast.png \
 EXAMPLES/OUTDIR1/2.bls \
 EXAMPLES/OUTDIR1/9.png \
 EXAMPLES/OUTDIR1/10.bls.model \
 EXAMPLES/OUTDIR1/InjectRRLyrae.5.txt \
 EXAMPLES/OUTDIR1/10.arimaresiduals.png \
 EXAMPLES/OUTDIR1/2.dftclean.dspec \
 EXAMPLES/OUTDIR1/2.test_tfa_nosr \
 EXAMPLES/OUTDIR1/9.autocorr \
 EXAMPLES/OUTDIR1/9.bls \
 EXAMPLES/OUTDIR1/10.sysrem.model \
 EXAMPLES/OUTDIR1/10.arimamodel \
 EXAMPLES/OUTDIR1/3.starspot.test_tfa_sr_bin \
 EXAMPLES/OUTDIR1/file_8_00008_simout.txt \
 EXAMPLES/OUTDIR1/2.aov_harm \
 EXAMPLES/OUTDIR1/1.arimaforecast.png \
 EXAMPLES/OUTDIR1/5.arimaresiduals.png \
 EXAMPLES/OUTDIR1/InjectRRLyrae.1.txt \
 EXAMPLES/OUTDIR1/sysrem.trends \
 EXAMPLES/OUTDIR1/2.png \
 EXAMPLES/OUTDIR1/file_5_00005_simout.txt \
 EXAMPLES/OUTDIR1/1.hjdutc \
 EXAMPLES/OUTDIR1/4.arimaforecast.png \
 EXAMPLES/OUTDIR1/kplr000757076-2009166043257_llc.asc.txt \
 EXAMPLES/OUTDIR1/3.injectharm.model \
 EXAMPLES/OUTDIR1/5.png \
 EXAMPLES/OUTDIR1/2.killharm.model \
 EXAMPLES/OUTDIR1/10.png \
 EXAMPLES/OUTDIR1/4.autocorr \
 EXAMPLES/OUTDIR1/2.tfa.model \
 EXAMPLES/OUTDIR1/4.phase.txt \
 EXAMPLES/OUTDIR1/1.autocorr \
 EXAMPLES/OUTDIR1/3.transit.blsfixdurtc.phcurve \
 EXAMPLES/OUTDIR1/2.mwwz \
 EXAMPLES/OUTDIR1/6.bls.phcurve \
 EXAMPLES/OUTDIR1/9.arimaresiduals.png \
 EXAMPLES/OUTDIR1/noisesim3.txt \
 EXAMPLES/OUTDIR1/2.test_tfa_sr_harm \
 EXAMPLES/OUTDIR1/7.arimamodel \
 EXAMPLES/OUTDIR1/1.tfa.model \
 EXAMPLES/OUTDIR1/3.png \
 EXAMPLES/OUTDIR1/4.cleanharm \
 EXAMPLES/OUTDIR1/tmp.txt.mcmc \
 EXAMPLES/OUTDIR1/3.maculainject \
 EXAMPLES/OUTDIR1/InjectRRLyrae.6.txt \
 EXAMPLES/OUTDIR1/8.cleanharm \
 EXAMPLES/OUTDIR1/8.png \
 EXAMPLES/OUTDIR1/file_1_00001_simout.txt \
 EXAMPLES/OUTDIR1/3.injecttransit.model \
 EXAMPLES/OUTDIR1/noisesim4.txt \
 EXAMPLES/OUTDIR1/1.test_tfa_sr_decorr \
 EXAMPLES/OUTDIR1/3.transit.mandelagoltransit.phcurve \
 EXAMPLES/OUTDIR1/6.bls.model \
 EXAMPLES/OUTDIR1/4.png \
 EXAMPLES/OUTDIR1/4.bls \
 EXAMPLES/OUTDIR1/3.transit.bls \
 EXAMPLES/OUTDIR1/5.phase.txt \
 EXAMPLES/OUTDIR1/3.transit.mandelagoltransit.model \
 EXAMPLES/OUTDIR1/2.tfa.coeff \
 EXAMPLES/OUTDIR1/7.bls.phcurve \
 EXAMPLES/OUTDIR1/3.bls \
 EXAMPLES/OUTDIR1/3.phase.txt \
 EXAMPLES/OUTDIR1/noisesim.txt \
 EXAMPLES/OUTDIR1/2.autocorr \
 EXAMPLES/OUTDIR1/2.phasebin.txt \
 EXAMPLES/OUTDIR1/1.arimaresiduals.png \
 EXAMPLES/OUTDIR1/9.arimaforecast.png \
 EXAMPLES/OUTDIR1/5.arimaforecast.png \
 EXAMPLES/OUTDIR1/8.bls.phcurve \
 EXAMPLES/OUTDIR1/3.autocorr \
 EXAMPLES/OUTDIR1/1.bls.phcurve \
 EXAMPLES/OUTDIR1/10.arimaforecast.png \
 EXAMPLES/OUTDIR1/2.bls.phcurve \
 EXAMPLES/OUTDIR1/8.autocorr \
 EXAMPLES/OUTDIR1/2.test_tfa_sr \
 EXAMPLES/OUTDIR1/9.cleanharm \
 EXAMPLES/OUTDIR1/3.mcmc \
 EXAMPLES/OUTDIR1/5.arimamodel \
 EXAMPLES/OUTDIR1/M3.V006.lc.killharm.model \
 EXAMPLES/OUTDIR1/10.autocorr \
 EXAMPLES/OUTDIR1/4.bls.phcurve \
 EXAMPLES/OUTDIR1/5.cleanharm \
 EXAMPLES/OUTDIR1/5.bls.phcurve \
 EXAMPLES/OUTDIR1/InjectRRLyrae.3.txt \
 EXAMPLES/OUTDIR1/2.cleanharm \
 EXAMPLES/OUTDIR1/file_6_00006_simout.txt \
 EXAMPLES/OUTDIR1/8.sysrem.model \
 EXAMPLES/OUTDIR1/noisesim2.txt \
 EXAMPLES/OUTDIR1/1.phase.txt \
 EXAMPLES/OUTDIR1/10.phase.txt \
 EXAMPLES/OUTDIR1/7.bls.model \
 EXAMPLES/OUTDIR1/4.dftclean.wfunc \
 EXAMPLES/OUTDIR1/4.bls.model \
 EXAMPLES/OUTDIR1/2.bls.model \
 EXAMPLES/OUTDIR1/InjectRRLyrae.10.txt \
 EXAMPLES/OUTDIR1/3.arimamodel \
 EXAMPLES/OUTDIR1/8.mwwz \
 EXAMPLES/OUTDIR1/7.autocorr \
 EXAMPLES/OUTDIR1/8.wwz \
 EXAMPLES/OUTDIR1/6.png \
 EXAMPLES/OUTDIR1/6.bls \
 EXAMPLES/OUTDIR1/3.transit.mandelagoltransit.jdcurve \
 EXAMPLES/OUTDIR1/5.sysrem.model \
 EXAMPLES/OUTDIR1/file_10_00010_simout.txt \
 EXAMPLES/OUTDIR1/6.arimaresiduals.png \
 EXAMPLES/OUTDIR1/3.nonlinfit.model \
 EXAMPLES/OUTDIR1/6.cleanharm \
 EXAMPLES/OUTDIR1/file_2_00002_simout.txt \
 EXAMPLES/OUTDIR1/8.bls \
 EXAMPLES/OUTDIR1/3.transit.bls.model \
 EXAMPLES/OUTDIR1/InjectRRLyrae.8.txt \
 EXAMPLES/OUTDIR1/file_7_00007_simout.txt \
 EXAMPLES/OUTDIR1/2.arimaresiduals.png \
 EXAMPLES/OUTDIR1/file_4_00004_simout.txt \
 EXAMPLES/OUTDIR1/7.phase.txt \
 EXAMPLES/OUTDIR1/7.sysrem.model \
 EXAMPLES/OUTDIR1/3.bls.model \
 EXAMPLES/OUTDIR1/1.tfa.coeff \
 EXAMPLES/OUTDIR1/3.cleanharm \
 EXAMPLES/OUTDIR1/4.dftclean.dspec \
 EXAMPLES/OUTDIR1/2.arimamodel \
 EXAMPLES/OUTDIR1/InjectRRLyrae.7.txt \
 EXAMPLES/OUTDIR1/8.phase.txt \
 EXAMPLES/OUTDIR1/1.arimamodel \
 EXAMPLES/OUTDIR1/5.autocorr \
 EXAMPLES/OUTDIR1/2.gls \
 EXAMPLES/OUTDIR1/3.phasebin.txt \
 EXAMPLES/OUTDIR1/8.bls.model \
 EXAMPLES/OUTDIR1/3.transit.bls.phcurve \
 EXAMPLES/OUTDIR1/file_9_00009_simout.txt \
 EXAMPLES/OUTDIR1/3.transit.softenedtransit.model \
 EXAMPLES/OUTDIR1/InjectRRLyrae.4.txt \
 EXAMPLES/OUTDIR1/4.dftclean.cspec \
 EXAMPLES/OUTDIR1/8.arimaresiduals.png \
 EXAMPLES/OUTDIR1/3.starspot.starspot.model \
 EXAMPLES/OUTDIR1/9.sysrem.model \
 EXAMPLES/OUTDIR1/4.sysrem.model \
 EXAMPLES/OUTDIR1/2.bin.txt \
 EXAMPLES/OUTDIR1/3.transit.blsfixdurtc \
 EXAMPLES/OUTDIR1/1.medianhighpass \
 EXAMPLES/OUTDIR1/1.cleanharm \
 EXAMPLES/OUTDIR1/7.png \
 EXAMPLES/OUTDIR1/2.wwz.fits \
 EXAMPLES/OUTDIR1/1.medianlowpass \
 EXAMPLES/OUTDIR1/2.aov \
 EXAMPLES/OUTDIR1/2.phase.txt \
 EXAMPLES/OUTDIR1/2.test_tfa_sr_bin \
 EXAMPLES/OUTDIR1/3.transit.blsfixdurtc.model \
 EXAMPLES/OUTDIR1/1.bls.model \
 EXAMPLES/OUTDIR1/10.bls.phcurve \
 EXAMPLES/OUTDIR1/InjectRRLyrae.2.txt \
 EXAMPLES/9 \
 EXAMPLES/7.fits \
 EXAMPLES/3 \
 EXAMPLES/4.gz \
 EXAMPLES/9.png \
 EXAMPLES/kplr000757076-2009166043257_llc.fits \
 EXAMPLES/lc_list_tfa_sr_bin \
 EXAMPLES/4 \
 EXAMPLES/2.testblend \
 EXAMPLES/8.fits \
 EXAMPLES/9.fits \
 EXAMPLES/2.png \
 EXAMPLES/lc_list_tfa_sr_harm \
 EXAMPLES/10.fits \
 EXAMPLES/5.png \
 EXAMPLES/10.png \
 EXAMPLES/2.resample.example2 \
 EXAMPLES/2.resample.example1 \
 EXAMPLES/11 \
 EXAMPLES/3.png \
 EXAMPLES/Rexample4.R~ \
 EXAMPLES/dates_tfa \
 EXAMPLES/10.gz \
 EXAMPLES/plotlc.py \
 EXAMPLES/11.highpassfftfilter \
 EXAMPLES/8.png \
 EXAMPLES/7 \
 EXAMPLES/M3.V006.lc \
 EXAMPLES/4.png \
 EXAMPLES/9.gz \
 EXAMPLES/3.maculacurve \
 EXAMPLES/4.resample.example3 \
 EXAMPLES/3.macula \
 EXAMPLES/8 \
 EXAMPLES/Rexample4.R \
 EXAMPLES/1.UTC \
 EXAMPLES/3.cliptransit \
 EXAMPLES/2.gz \
 EXAMPLES/lc_list_tfa \
 EXAMPLES/lc_list_testblend \
 EXAMPLES/trendlist_tfa \
 EXAMPLES/lc_list \
 EXAMPLES/4.fits \
 EXAMPLES/lc_list_gz \
 EXAMPLES/1 \
 EXAMPLES/5.gz \
 EXAMPLES/6.png \
 EXAMPLES/2.fits \
 EXAMPLES/4.microlensinject \
 EXAMPLES/5 \
 EXAMPLES/10 \
 EXAMPLES/3.transit \
 EXAMPLES/1.resample.example4 \
 EXAMPLES/lc_list_tfa_sr_decorr \
 EXAMPLES/6 \
 EXAMPLES/7.png \
 EXAMPLES/3.transit.fits \
 EXAMPLES/6.gz \
 EXAMPLES/3.starspot
